spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: gandazhi
    url: jdbc:mysql://127.0.0.1:3306/wx_takeaway?characterEncoding=utf-8&useSSL=false
server:
  context-path: /sell
mybatis:
  mapperLocations: classpath:/resources/mappers/*.xml
  typeAliasesPackage: com.gandazhi.sell.pojo



