spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: gandazhi
    url: jdbc:mysql://127.0.0.1:3306/wx_takeaway?characterEncoding=utf-8&useSSL=false
  redis:
      host: 127.0.0.1
      port: 6379
server:
  context-path: /sell
mybatis:
    # 配置类型别名
    typeAliasesPackage: com.gandazhi.sell.pojo
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mappers/*Mapper.xml
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: countSql




